name: Build via SSH

on: 
  push:
    tags:
      - "*"  

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Sync
        run: zsh ~/sync.sh

      - name: Clean
        run: |
          cd /Android/rr
          make clobber

      - name: Build
        run: |
          zsh ~/build.sh

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            /Android/rr/out/target/product/cepheus/RROS*

